### PR TITLE
Add support for tsconfigPath setting

### PR DESCRIPTION
**Pull request by nateroling**
This adds support for a new "tsconfigPath" setting for tsserver.

### CODE REVIEW

**Comment by chemzqm** [comment]
It's not "tsconfigPath" setting for tsserver, but only tsconfig path fro `tsserver.watchBuild` command, please add description in package.json.

**Comment by nateroling** [comment]
Good point, updated. Do you think the setting name should change too, or is `tsconfigPath` good?

**Comment by ridgekuhn** [comment]
I'm sorry to necropost, but how do I use this feature? Is the `watchBuild` command a separate thing than simply opening a typescript file with `coc-tsserver` installed? I've set `tsconfigPath` in my CoC local config and confirmed the config is getting parsed, but if I run `:CocCommand tsserver.openTsServerLog` after opening a typescript file, there's no mention of `tsconfig.test.json`, only `tsconfig.json`. I'm also not seeing [this error message](https://github.com/neoclide/coc-tsserver/blob/7c8da78691bbc56cc0cca9d71eb03f325dc3ea3c/src/server/watchBuild.ts#L114) in the log. Am I missing something?

```{
  "tsserver": {
    "enable": true,
    "log": "verbose",
    "tsconfigPath": "tsconfig.test.json"
  }
}
```

**Comment by chemzqm** [comment]
>  Is the watchBuild command a separate thing than simply opening a typescript file with coc-tsserver installed?

That command compile your typescript files by run `tsc --watch` command as a vim job.

**Comment by ridgekuhn** [comment]
@ chemzqm Thanks for your response! So there is currently no way to use a custom tsconfig path for normal vim editing then?

**Comment by chemzqm** [comment]
Configuration `"tsserver.tsconfigPath": "tsconfig.test.json"` should works.

**Comment by ridgekuhn** [comment]
@chemzqm Unfortunately I can't seem to get it to work whether it's in the local project's CoC config or the global CoC config. I will keep trying to troubleshoot and open an issue if I can't find anything wrong. Thanks so much for your time and help!

**Pull request merged**
