### PR TITLE
feat(commands): Go to Source Definition

### LINKED ISSUE #383: Support new "Go to Source Definition" feature in TS 4.7
The readme for this repo mentions that goto definition does always work correctly and often drops you into a .d.ts file rather than the actual definition. It looks like they added the ability to go to a real definition in 4.7, but unfortunately as a new custom command, rather than as the default goToDefinition behavior. It would be nice if there was some way to access this functionality from coc-tsserver. If there already is, I couldn't figure it out 😄.

More info:
[Blog announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#go-to-source-definition)
[Feedback Thread](https://github.com/microsoft/TypeScript/issues/49003)
[Implementation PR](https://github.com/microsoft/TypeScript/pull/48264)

### PR DESCRIPTION
**Pull request by fannheyward**
`tsserver.goToSourceDefinition`, close #383

### CODE REVIEW

**Comment by sandrodz** [comment]
This is awesome, hopefully it gets in soon.

**Comment by sandrodz** [comment]
@fannheyward how do we make this work with vim's `gd` only in TS files?

**Comment by chemzqm** [comment]
You can create buffer key-mappings `:h map-buffer`

**Comment by fabOnReact** [comment]
go to the definition does not work with libraries like React.js 

https://github.com/microsoft/TypeScript/issues/37777#issuecomment-2259714084

https://github.com/user-attachments/assets/35636636-31aa-4ad3-88ab-187176e12b4b


for example, I can not navigate the source code implementation of useRef. It is minified.

**Pull request merged**
